-- Seed the library catalog
INSERT INTO "categories" ("name") VALUES
  ('Spiritual'),
  ('Murder-Mystery'),
  ('Realistic'),
  ('Science Fiction'),
  ('History'),
  ('Self-Help'),
  ('Fantasy'),
  ('Romance'),
  ('Technology');
INSERT INTO "books" ("title", "author", "copies", "max_borrow_days", "category_id") VALUES
  ('Autobiography of Yogi', 'Paramahansa Yogananda', 3, 7, (SELECT "id" FROM "categories" WHERE "name" = 'Spiritual')),
  ('Bhagavad Gita', 'Ved Vyasa', 2, 5, (SELECT "id" FROM "categories" WHERE "name" = 'Spiritual')),
  ('The Power of Now', 'Eckhart Tolle', 4, 8, (SELECT "id" FROM "categories" WHERE "name" = 'Spiritual')),
  ('Meditations', 'Marcus Aurelius', 2, 10, (SELECT "id" FROM "categories" WHERE "name" = 'Spiritual')),
  ('Sherlock Holmes', 'Arthur Conan Doyle', 2, 5, (SELECT "id" FROM "categories" WHERE "name" = 'Murder-Mystery')),
  ('Gone Girl', 'Gillian Flynn', 1, 4, (SELECT "id" FROM "categories" WHERE "name" = 'Murder-Mystery')),
  ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 3, 7, (SELECT "id" FROM "categories" WHERE "name" = 'Murder-Mystery')),
  ('And Then There Were None', 'Agatha Christie', 2, 6, (SELECT "id" FROM "categories" WHERE "name" = 'Murder-Mystery')),
  ('Rich Dad Poor Dad', 'Robert Kiyosaki', 4, 10, (SELECT "id" FROM "categories" WHERE "name" = 'Realistic')),
  ('The Alchemist', 'Paulo Coelho', 2, 6, (SELECT "id" FROM "categories" WHERE "name" = 'Realistic')),
  ('1984', 'George Orwell', 3, 8, (SELECT "id" FROM "categories" WHERE "name" = 'Realistic')),
  ('To Kill a Mockingbird', 'Harper Lee', 2, 7, (SELECT "id" FROM "categories" WHERE "name" = 'Realistic')),
  ('Dune', 'Frank Herbert', 3, 14, (SELECT "id" FROM "categories" WHERE "name" = 'Science Fiction')),
  ('Neuromancer', 'William Gibson', 2, 10, (SELECT "id" FROM "categories" WHERE "name" = 'Science Fiction')),
  ('Foundation', 'Isaac Asimov', 2, 12, (SELECT "id" FROM "categories" WHERE "name" = 'Science Fiction')),
  ('The Martian', 'Andy Weir', 4, 8, (SELECT "id" FROM "categories" WHERE "name" = 'Science Fiction')),
  ('Sapiens', 'Yuval Noah Harari', 2, 12, (SELECT "id" FROM "categories" WHERE "name" = 'History')),
  ('Guns, Germs, and Steel', 'Jared Diamond', 1, 14, (SELECT "id" FROM "categories" WHERE "name" = 'History')),
  ('A Brief History of Time', 'Stephen Hawking', 3, 10, (SELECT "id" FROM "categories" WHERE "name" = 'History')),
  ('The Silk Roads', 'Peter Frankopan', 2, 11, (SELECT "id" FROM "categories" WHERE "name" = 'History')),
  ('Atomic Habits', 'James Clear', 4, 7, (SELECT "id" FROM "categories" WHERE "name" = 'Self-Help')),
  ('The Power of Habit', 'Charles Duhigg', 3, 7, (SELECT "id" FROM "categories" WHERE "name" = 'Self-Help')),
  ('Thinking, Fast and Slow', 'Daniel Kahneman', 2, 9, (SELECT "id" FROM "categories" WHERE "name" = 'Self-Help')),
  ('Mindset', 'Carol S. Dweck', 3, 8, (SELECT "id" FROM "categories" WHERE "name" = 'Self-Help')),
  ('The Hobbit', 'J.R.R. Tolkien', 3, 10, (SELECT "id" FROM "categories" WHERE "name" = 'Fantasy')),
  ('Harry Potter', 'J.K. Rowling', 5, 12, (SELECT "id" FROM "categories" WHERE "name" = 'Fantasy')),
  ('The Name of the Wind', 'Patrick Rothfuss', 2, 11, (SELECT "id" FROM "categories" WHERE "name" = 'Fantasy')),
  ('A Game of Thrones', 'George R.R. Martin', 2, 14, (SELECT "id" FROM "categories" WHERE "name" = 'Fantasy')),
  ('Pride and Prejudice', 'Jane Austen', 2, 8, (SELECT "id" FROM "categories" WHERE "name" = 'Romance')),
  ('The Notebook', 'Nicholas Sparks', 2, 7, (SELECT "id" FROM "categories" WHERE "name" = 'Romance')),
  ('Outlander', 'Diana Gabaldon', 3, 9, (SELECT "id" FROM "categories" WHERE "name" = 'Romance')),
  ('Jane Eyre', 'Charlotte Brontë', 2, 8, (SELECT "id" FROM "categories" WHERE "name" = 'Romance')),
  ('The Lean Startup', 'Eric Ries', 3, 10, (SELECT "id" FROM "categories" WHERE "name" = 'Technology')),
  ('Zero to One', 'Peter Thiel', 2, 9, (SELECT "id" FROM "categories" WHERE "name" = 'Technology')),
  ('Code Complete', 'Steve McConnell', 1, 12, (SELECT "id" FROM "categories" WHERE "name" = 'Technology')),
  ('The Pragmatic Programmer', 'Dave Thomas & Andy Hunt', 2, 10, (SELECT "id" FROM "categories" WHERE "name" = 'Technology'));
